# Generated by Django 5.0.2 on 2024-03-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
